name: Lean CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Lean CI
        uses: leanprover/lean-action@v1
        with:
          use-mathlib-cache: true
